services:
  test:
    depends_on:
      worker:
        condition: service_healthy
    build:
      context: .
      dockerfile_inline: |
        FROM denoland/deno:alpine-2.5.3
        RUN apk add --no-cache curl bash
    command: deno test --trace-leaks --watch --unsafely-ignore-certificate-errors --allow-all --unstable-cron --unstable-kv .
    working_dir: /app/app/test
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - IGNORE_CERTIFICATE_ERRORS=true
      - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-}
      - API_URL=http://worker:8000
      - QUEUE_ID=local
      - DENO_DIR=/deno
      - DENO_INSTALL_ROOT=/deno
    volumes:
      - deno:/deno
      - .:/app
    networks:
      - default
    logging:
      driver: ${LOGGING_TESTS:-json-file}
