name: fmt and lint

on:
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.5.0"

      - name: Setup Just CLI
        uses: extractions/setup-just@v1
        with:
          just-version: "1.35.0"

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.5.3"

      - name: Build shared
        run: just shared build

      - name: Check formatting and linting
        run: just ci
