name: Publish worker binary & container images

on:
  push:
    branches:
      - "main"
    paths:
      - "app/worker/mod.json"

jobs:
  release-worker-binary:
    name: Build and release worker binary
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup Just CLI
        uses: extractions/setup-just@v1
        with:
          just-version: "1.35.0"

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.5.3"

      - name: Build and release
        env:
          GH_TOKEN: ${{ github.token }}
        run: just app/worker/publish-binary

  publish-worker-images:
    name: Build and push worker container images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup Just CLI
        uses: extractions/setup-just@v1
        with:
          just-version: "1.35.0"

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.5.3"

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and release
        run: just publish-versioned-artifacts
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version from mod.json
        id: get-version
        run: |
          VERSION=$(cat app/worker/mod.json | jq -r '.version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create and push git tag
        run: |
          git tag ${{ steps.get-version.outputs.version }}
          git push origin ${{ steps.get-version.outputs.version }}
